module.exports = [
  'Afeganistão',
  'Alanda',
  'Albânia',
  'Alemanha',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antártida',
  'Antígua e Barbuda',
  'Argentina',
  'Argélia',
  'Armênia',
  'Aruba',
  'Arábia Saudita',
  'Austrália',
  'Azerbaijão',
  'Bahamas',
  'Bahrain',
  'Bangladexe',
  'Barbados',
  'Belize',
  'Benin',
  'Bermudas',
  'Bielo-Rússia',
  'Bolívia',
  'Bonaire',
  'Botsuana',
  'Brasil',
  'Brunei',
  'Bulgária',
  'Burkina Fasso',
  'Burundi',
  'Butão',
  'Bélgica',
  'Bósnia-Herzegóvina',
  'Cabo Verde',
  'Camarões',
  'Camboja',
  'Canadá',
  'Catar',
  'Cazaquistão',
  'Chade',
  'Chile',
  'China',
  'Chipre',
  'Cingapura',
  'Colômbia',
  'Congo',
  'Congo-Kinshasa',
  'Coreia do Norte',
  'Coreia do Sul',
  'Costa Rica',
  'Costa do Marfim',
  'Croácia',
  'Cuba',
  'Curaçao',
  'Dinamarca',
  'Djibuti',
  'Dominica',
  'Egito',
  'El Salvador',
  'Emirados Árabes Unidos',
  'Equador',
  'Eritreia',
  'Eslováquia',
  'Eslovênia',
  'Espanha',
  'Estados Unidos',
  'Estônia',
  'Etiópia',
  'Fiji',
  'Filipinas',
  'Finlândia',
  'França',
  'Gabão',
  'Gana',
  'Geórgia',
  'Geórgia do Sul e Ilhas Sandwich do Sul',
  'Gibraltar',
  'Granada',
  'Gronelândia',
  'Grécia',
  'Guadalupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guiana',
  'Guiana Francesa',
  'Guiné',
  'Guiné Equatorial',
  'Gâmbia',
  'Haiti',
  'Holanda',
  'Honduras',
  'Hong Kong',
  'Hungria',
  'Ilha Bouvet',
  'Ilha Heard e Ilhas McDonald',
  'Ilha Norfolk',
  'Ilha de Man',
  'Ilhas Caiman',
  'Ilhas Coco',
  'Ilhas Comores',
  'Ilhas Cook',
  'Ilhas Faroe',
  'Ilhas Malvinas',
  'Ilhas Marianas do Norte',
  'Ilhas Marshall',
  'Ilhas Menores Distantes dos Estados Unidos',
  'Ilhas Natal',
  'Ilhas Salomão',
  'Ilhas Seychelles',
  'Ilhas Turks e Caicos',
  'Ilhas Virgens Britânicas',
  'Ilhas Virgens dos EUA',
  'Ilhas Wallis e Futuna',
  'Indonésia',
  'Iraque',
  'Irlanda',
  'Irã',
  'Islândia',
  'Israel',
  'Itália',
  'Iêmen',
  'Jamaica',
  'Japão',
  'Jersey',
  'Jordânia',
  'Kosovo',
  'Kuwait',
  'Lesoto',
  'Letônia',
  'Libéria',
  'Lichtenstein',
  'Lituânia',
  'Luxemburgo',
  'Líbano',
  'Líbia Árabe Jamahiriya',
  'Macedônia',
  'Madagascar',
  'Malauí',
  'Maldivas',
  'Mali',
  'Malta',
  'Malásia',
  'Marrocos',
  'Martinica',
  'Mauritânia',
  'Maurício',
  'Mayotte',
  'Mianmar [Birmânia]',
  'Micronésia',
  'Moldova, República de',
  'Mongólia',
  'Montenegro',
  'Montserrat',
  'México',
  'Mónaco',
  'Namíbia',
  'Nauru',
  'Nepal',
  'Nicarágua',
  'Nigéria',
  'Niue',
  'Noruega',
  'Nova Caledônia',
  'Nova Zelândia',
  'Níger',
  'Omã',
  'Palau',
  'Panamá',
  'Papua-Nova Guiné',
  'Paquistão',
  'Paraguai',
  'Peru',
  'Pitcairn',
  'Polinésia Francesa',
  'Polônia',
  'Porto Rico',
  'Portugal',
  'Quirguistão',
  'Quiribati',
  'Quênia',
  'Região Administrativa Especial de Macau',
  'Reino Unido',
  'República Centro-Africana',
  'República Democrática de São Tomé e Príncipe',
  'República Democrática de Timor-Leste',
  'República Dominicana',
  'República Popular Democrática do Laos',
  'República da Guiné-Bissau',
  'República de Moçambique',
  'Reunião',
  'Romênia',
  'Ruanda',
  'Rússia',
  'Saara Ocidental',
  'Saint Pierre e Miquelon',
  'Samoa',
  'Samoa Americana',
  'San Marino',
  'Santa Helena',
  'Santa Lúcia',
  'Senegal',
  'Serra Leoa',
  'Somália',
  'Sri Lanka',
  'Suazilândia',
  'Sudão',
  'Sudão do Sul',
  'Suriname',
  'Suécia',
  'Suíça',
  'Svalbard e Jan Mayen',
  'São Bartolomeu',
  'São Cristóvão e Névis',
  'São Martinho',
  'São Martinho',
  'São Vincente e Granadinas',
  'Sérvia',
  'Síria',
  'Tailândia',
  'Taiwan',
  'Tajiquistão',
  'Tanzânia',
  'Tchéquia',
  'Território Britânico do Oceano Índico',
  'Territórios Franceses do Sul',
  'Territórios palestinos',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trindade e Tobago',
  'Tunísia',
  'Turcomenistão',
  'Turquia',
  'Tuvalu',
  'Ucrânia',
  'Uganda',
  'Uruguai',
  'Uzbequistão',
  'Vanuatu',
  'Vaticano',
  'Venezuela',
  'Vietnã',
  'Zimbábue',
  'Zâmbia',
  'África do Sul',
  'Áustria',
  'Índia'
]
