module.exports = {
  AD: 'Andorra',
  AE: 'Emirados Árabes Unidos',
  AF: 'Afeganistão',
  AG: 'Antígua e Barbuda',
  AI: 'Anguilla',
  AL: 'Albânia',
  AM: 'Armênia',
  AO: 'Angola',
  AQ: 'Antártida',
  AR: 'Argentina',
  AS: 'Samoa Americana',
  AT: 'Áustria',
  AU: 'Austrália',
  AW: 'Aruba',
  AX: 'Alanda',
  AZ: 'Azerbaijão',
  BA: 'Bósnia-Herzegóvina',
  BB: 'Barbados',
  BD: 'Bangladexe',
  BE: 'Bélgica',
  BF: 'Burkina Fasso',
  BG: 'Bulgária',
  BH: 'Bahrain',
  BI: 'Burundi',
  BJ: 'Benin',
  BL: 'São Bartolomeu',
  BM: 'Bermudas',
  BN: 'Brunei',
  BO: 'Bolívia',
  BQ: 'Bonaire',
  BR: 'Brasil',
  BS: 'Bahamas',
  BT: 'Butão',
  BV: 'Ilha Bouvet',
  BW: 'Botsuana',
  BY: 'Bielo-Rússia',
  BZ: 'Belize',
  CA: 'Canadá',
  CC: 'Ilhas Coco',
  CD: 'Congo-Kinshasa',
  CF: 'República Centro-Africana',
  CG: 'Congo',
  CH: 'Suíça',
  CI: 'Costa do Marfim',
  CK: 'Ilhas Cook',
  CL: 'Chile',
  CM: 'Camarões',
  CN: 'China',
  CO: 'Colômbia',
  CR: 'Costa Rica',
  CU: 'Cuba',
  CV: 'Cabo Verde',
  CW: 'Curaçao',
  CX: 'Ilhas Natal',
  CY: 'Chipre',
  CZ: 'Tchéquia',
  DE: 'Alemanha',
  DJ: 'Djibuti',
  DK: 'Dinamarca',
  DM: 'Dominica',
  DO: 'República Dominicana',
  DZ: 'Argélia',
  EC: 'Equador',
  EE: 'Estônia',
  EG: 'Egito',
  EH: 'Saara Ocidental',
  ER: 'Eritreia',
  ES: 'Espanha',
  ET: 'Etiópia',
  FI: 'Finlândia',
  FJ: 'Fiji',
  FK: 'Ilhas Malvinas',
  FM: 'Micronésia',
  FO: 'Ilhas Faroe',
  FR: 'França',
  GA: 'Gabão',
  GB: 'Reino Unido',
  GD: 'Granada',
  GE: 'Geórgia',
  GF: 'Guiana Francesa',
  GG: 'Guernsey',
  GH: 'Gana',
  GI: 'Gibraltar',
  GL: 'Gronelândia',
  GM: 'Gâmbia',
  GN: 'Guiné',
  GP: 'Guadalupe',
  GQ: 'Guiné Equatorial',
  GR: 'Grécia',
  GS: 'Geórgia do Sul e Ilhas Sandwich do Sul',
  GT: 'Guatemala',
  GU: 'Guam',
  GW: 'República da Guiné-Bissau',
  GY: 'Guiana',
  HK: 'Hong Kong',
  HM: 'Ilha Heard e Ilhas McDonald',
  HN: 'Honduras',
  HR: 'Croácia',
  HT: 'Haiti',
  HU: 'Hungria',
  ID: 'Indonésia',
  IE: 'Irlanda',
  IL: 'Israel',
  IM: 'Ilha de Man',
  IN: 'Índia',
  IO: 'Território Britânico do Oceano Índico',
  IQ: 'Iraque',
  IR: 'Irã',
  IS: 'Islândia',
  IT: 'Itália',
  JE: 'Jersey',
  JM: 'Jamaica',
  JO: 'Jordânia',
  JP: 'Japão',
  KE: 'Quênia',
  KG: 'Quirguistão',
  KH: 'Camboja',
  KI: 'Quiribati',
  KM: 'Ilhas Comores',
  KN: 'São Cristóvão e Névis',
  KP: 'Coreia do Norte',
  KR: 'Coreia do Sul',
  KW: 'Kuwait',
  KY: 'Ilhas Caiman',
  KZ: 'Cazaquistão',
  LA: 'República Popular Democrática do Laos',
  LB: 'Líbano',
  LC: 'Santa Lúcia',
  LI: 'Lichtenstein',
  LK: 'Sri Lanka',
  LR: 'Libéria',
  LS: 'Lesoto',
  LT: 'Lituânia',
  LU: 'Luxemburgo',
  LV: 'Letônia',
  LY: 'Líbia Árabe Jamahiriya',
  MA: 'Marrocos',
  MC: 'Mónaco',
  MD: 'Moldova, República de',
  ME: 'Montenegro',
  MF: 'São Martinho',
  MG: 'Madagascar',
  MH: 'Ilhas Marshall',
  MK: 'Macedônia',
  ML: 'Mali',
  MM: 'Mianmar [Birmânia]',
  MN: 'Mongólia',
  MO: 'Região Administrativa Especial de Macau',
  MP: 'Ilhas Marianas do Norte',
  MQ: 'Martinica',
  MR: 'Mauritânia',
  MS: 'Montserrat',
  MT: 'Malta',
  MU: 'Maurício',
  MV: 'Maldivas',
  MW: 'Malauí',
  MX: 'México',
  MY: 'Malásia',
  MZ: 'República de Moçambique',
  NA: 'Namíbia',
  NC: 'Nova Caledônia',
  NE: 'Níger',
  NF: 'Ilha Norfolk',
  NG: 'Nigéria',
  NI: 'Nicarágua',
  NL: 'Holanda',
  NO: 'Noruega',
  NP: 'Nepal',
  NR: 'Nauru',
  NU: 'Niue',
  NZ: 'Nova Zelândia',
  OM: 'Omã',
  PA: 'Panamá',
  PE: 'Peru',
  PF: 'Polinésia Francesa',
  PG: 'Papua-Nova Guiné',
  PH: 'Filipinas',
  PK: 'Paquistão',
  PL: 'Polônia',
  PM: 'Saint Pierre e Miquelon',
  PN: 'Pitcairn',
  PR: 'Porto Rico',
  PS: 'Territórios palestinos',
  PT: 'Portugal',
  PW: 'Palau',
  PY: 'Paraguai',
  QA: 'Catar',
  RE: 'Reunião',
  RO: 'Romênia',
  RS: 'Sérvia',
  RU: 'Rússia',
  RW: 'Ruanda',
  SA: 'Arábia Saudita',
  SB: 'Ilhas Salomão',
  SC: 'Ilhas Seychelles',
  SD: 'Sudão',
  SE: 'Suécia',
  SG: 'Cingapura',
  SH: 'Santa Helena',
  SI: 'Eslovênia',
  SJ: 'Svalbard e Jan Mayen',
  SK: 'Eslováquia',
  SL: 'Serra Leoa',
  SM: 'San Marino',
  SN: 'Senegal',
  SO: 'Somália',
  SR: 'Suriname',
  SS: 'Sudão do Sul',
  ST: 'República Democrática de São Tomé e Príncipe',
  SV: 'El Salvador',
  SX: 'São Martinho',
  SY: 'Síria',
  SZ: 'Suazilândia',
  TC: 'Ilhas Turks e Caicos',
  TD: 'Chade',
  TF: 'Territórios Franceses do Sul',
  TG: 'Togo',
  TH: 'Tailândia',
  TJ: 'Tajiquistão',
  TK: 'Tokelau',
  TL: 'República Democrática de Timor-Leste',
  TM: 'Turcomenistão',
  TN: 'Tunísia',
  TO: 'Tonga',
  TR: 'Turquia',
  TT: 'Trindade e Tobago',
  TV: 'Tuvalu',
  TW: 'Taiwan',
  TZ: 'Tanzânia',
  UA: 'Ucrânia',
  UG: 'Uganda',
  UM: 'Ilhas Menores Distantes dos Estados Unidos',
  US: 'Estados Unidos',
  UY: 'Uruguai',
  UZ: 'Uzbequistão',
  VA: 'Vaticano',
  VC: 'São Vincente e Granadinas',
  VE: 'Venezuela',
  VG: 'Ilhas Virgens Britânicas',
  VI: 'Ilhas Virgens dos EUA',
  VN: 'Vietnã',
  VU: 'Vanuatu',
  WF: 'Ilhas Wallis e Futuna',
  WS: 'Samoa',
  XK: 'Kosovo',
  YE: 'Iêmen',
  YT: 'Mayotte',
  ZA: 'África do Sul',
  ZM: 'Zâmbia',
  ZW: 'Zimbábue'
}
