export default () => ([
  'Afeganistao',
  'Africa do Sul',
  'Alanda',
  'Albania',
  'Alemanha',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antartida',
  'Antigua e Barbuda',
  'Arabia Saudita',
  'Argelia',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijao',
  'Bahamas',
  'Bahrain',
  'Bangladexe',
  'Barbados',
  'Belgica',
  'Belize',
  'Benin',
  'Bermudas',
  'Bielo-Russia',
  'Bolivia',
  'Bonaire',
  'Bosnia-Herzegovina',
  'Botsuana',
  'Brasil',
  'Brunei',
  'Bulgaria',
  'Burkina Fasso',
  'Burundi',
  'Butao',
  'Cabo Verde',
  'Camaroes',
  'Camboja',
  'Canada',
  'Catar',
  'Cazaquistao',
  'Chade',
  'Chile',
  'China',
  'Chipre',
  'Cingapura',
  'Colombia',
  'Congo',
  'Congo-Kinshasa',
  'Coreia do Norte',
  'Coreia do Sul',
  'Costa Rica',
  'Costa do Marfim',
  'Croacia',
  'Cuba',
  'Curacao',
  'Dinamarca',
  'Djibuti',
  'Dominica',
  'Egito',
  'El Salvador',
  'Emirados Arabes Unidos',
  'Equador',
  'Eritreia',
  'Eslovaquia',
  'Eslovenia',
  'Espanha',
  'Estados Unidos',
  'Estonia',
  'Etiopia',
  'Fiji',
  'Filipinas',
  'Finlandia',
  'Franca',
  'Gabao',
  'Gambia',
  'Gana',
  'Georgia',
  'Georgia do Sul e Ilhas Sandwich do Sul',
  'Gibraltar',
  'Granada',
  'Grecia',
  'Gronelandia',
  'Guadalupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guiana',
  'Guiana Francesa',
  'Guine',
  'Guine Equatorial',
  'Haiti',
  'Holanda',
  'Honduras',
  'Hong Kong',
  'Hungria',
  'Iemen',
  'Ilha Bouvet',
  'Ilha Heard e Ilhas McDonald',
  'Ilha Norfolk',
  'Ilha de Man',
  'Ilhas Caiman',
  'Ilhas Coco',
  'Ilhas Comores',
  'Ilhas Cook',
  'Ilhas Faroe',
  'Ilhas Malvinas',
  'Ilhas Marianas do Norte',
  'Ilhas Marshall',
  'Ilhas Menores Distantes dos Estados Unidos',
  'Ilhas Natal',
  'Ilhas Salomao',
  'Ilhas Seychelles',
  'Ilhas Turks e Caicos',
  'Ilhas Virgens Britanicas',
  'Ilhas Virgens dos EUA',
  'Ilhas Wallis e Futuna',
  'India',
  'Indonesia',
  'Ira',
  'Iraque',
  'Irlanda',
  'Islandia',
  'Israel',
  'Italia',
  'Jamaica',
  'Japao',
  'Jersey',
  'Jordania',
  'Kosovo',
  'Kuwait',
  'Lesoto',
  'Letonia',
  'Libano',
  'Liberia',
  'Libia Arabe Jamahiriya',
  'Lichtenstein',
  'Lituania',
  'Luxemburgo',
  'Macedonia',
  'Madagascar',
  'Malasia',
  'Malaui',
  'Maldivas',
  'Mali',
  'Malta',
  'Marrocos',
  'Martinica',
  'Mauricio',
  'Mauritania',
  'Mayotte',
  'Mexico',
  'Mianmar [Birmania]',
  'Micronesia',
  'Moldova, Republica de',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Namibia',
  'Nauru',
  'Nepal',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Noruega',
  'Nova Caledonia',
  'Nova Zelandia',
  'Oma',
  'Palau',
  'Panama',
  'Papua-Nova Guine',
  'Paquistao',
  'Paraguai',
  'Peru',
  'Pitcairn',
  'Polinesia Francesa',
  'Polonia',
  'Porto Rico',
  'Portugal',
  'Quenia',
  'Quirguistao',
  'Quiribati',
  'Regiao Administrativa Especial de Macau',
  'Reino Unido',
  'Republica Centro-Africana',
  'Republica Democratica de Sao Tome e Principe',
  'Republica Democratica de Timor-Leste',
  'Republica Dominicana',
  'Republica Popular Democratica do Laos',
  'Republica da Guine-Bissau',
  'Republica de Mocambique',
  'Reuniao',
  'Romenia',
  'Ruanda',
  'Russia',
  'Saara Ocidental',
  'Saint Pierre e Miquelon',
  'Samoa',
  'Samoa Americana',
  'San Marino',
  'Santa Helena',
  'Santa Lucia',
  'Sao Bartolomeu',
  'Sao Cristovao e Nevis',
  'Sao Martinho',
  'Sao Martinho2',
  'Sao Vincente e Granadinas',
  'Senegal',
  'Serra Leoa',
  'Servia',
  'Siria',
  'Somalia',
  'Sri Lanka',
  'Suazilandia',
  'Sudao',
  'Sudao do Sul',
  'Suecia',
  'Suica',
  'Suriname',
  'Svalbard e Jan Mayen',
  'Tailandia',
  'Taiwan',
  'Tajiquistao',
  'Tanzania',
  'Tchequia',
  'Territorio Britanico do Oceano Indico',
  'Territorios Franceses do Sul',
  'Territorios palestinos',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trindade e Tobago',
  'Tunisia',
  'Turcomenistao',
  'Turquia',
  'Tuvalu',
  'Ucrania',
  'Uganda',
  'Uruguai',
  'Uzbequistao',
  'Vanuatu',
  'Vaticano',
  'Venezuela',
  'Vietna',
  'Zambia',
  'Zimbabue'
])
