export default [
  'Afghanistan',
  'Alandinseln',
  'Albanien',
  'Algerien',
  'Amerikanisch-Ozeanien',
  'Amerikanisch-Samoa',
  'Amerikanische Jungferninseln',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarktis',
  'Antigua und Barbuda',
  'Argentinien',
  'Armenien',
  'Aruba',
  'Aserbaidschan',
  'Australien',
  'Bahamas',
  'Bahrain',
  'Bangladesch',
  'Barbados',
  'Belgien',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Birma (Myanmar)',
  'Bolivien',
  'Bonaire',
  'Bosnien und Herzegowina',
  'Botswana',
  'Bouvetinsel',
  'Brasilien',
  'Britische Jungferninseln',
  'Britisches Territorium im Indischen Ozean',
  'Brunei',
  'Bulgarien',
  'Burkina Faso',
  'Burundi',
  'Chile',
  'China',
  'Cookinseln',
  'Costa Rica',
  'Curaçao',
  'Deutschland',
  'Dom. Republik',
  'Dominica',
  'Dschibuti',
  'Dänemark',
  'Ecuador',
  'Ehemalige jugoslawische Republik Mazedonien',
  'El Salvador',
  'Elfenbeinküste',
  'Eritrea',
  'Estland',
  'Falklandinseln',
  'Fidschi',
  'Finnland',
  'Frankreich',
  'Französisch-Guayana',
  'Französisch-Polynesien',
  'Französische Süd- und Antarktisgebiete',
  'Färöer-Inseln',
  'Gabun',
  'Gambia',
  'Georgien',
  'Ghana',
  'Gibraltar',
  'Grenada',
  'Griechenland',
  'Grönland',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard- und McDonald-Inseln',
  'Honduras',
  'Hongkong',
  'Indien',
  'Indonesien',
  'Insel Man',
  'Irak',
  'Iran (Islamische Republik)',
  'Irland',
  'Island',
  'Israel',
  'Italien',
  'Jamaika',
  'Japan',
  'Jemen',
  'Jersey',
  'Jordanien',
  'Kaimaninseln',
  'Kambodscha',
  'Kamerun',
  'Kanada',
  'Kapverden',
  'Kasachstan',
  'Katar',
  'Kenia',
  'Kirgistan',
  'Kiribati',
  'Kokosinseln',
  'Kolumbien',
  'Komoren',
  'Kongo',
  'Kongo (Republik Kongo)',
  'Kosovo',
  'Kroatien',
  'Kuba',
  'Kuwait',
  'Laos',
  'Lesotho',
  'Lettland',
  'Libanon',
  'Liberia',
  'Libysch-Arabische Dschamahirija',
  'Liechtenstein',
  'Litauen',
  'Luxemburg',
  'Macau',
  'Madagaskar',
  'Malawi',
  'Malaysia',
  'Malediven',
  'Mali',
  'Malta',
  'Marokko',
  'Marshall-Inseln',
  'Martinique',
  'Mauretanien',
  'Mauritius',
  'Mayotte',
  'Mexiko',
  'Mikronesien',
  'Moldau (Republik Moldau)',
  'Monaco',
  'Mongolei',
  'Montenegro',
  'Montserrat',
  'Mosambik',
  'Namibia',
  'Nauru',
  'Nepal',
  'Neukaledonien',
  'Neuseeland',
  'Niederlande',
  'Niger',
  'Nigeria',
  'Nikaragua',
  'Niue',
  'Nordkorea',
  'Norfolkinsel',
  'Norwegen',
  'Nördliche Marianen',
  'Oman',
  'Pakistan',
  'Palau',
  'Palästinensische Autonomiegebiete',
  'Panama',
  'Papua-Neuguinea',
  'Paraguay',
  'Peru',
  'Philippinen',
  'Pitcairn',
  'Polen',
  'Portugal',
  'Puerto Rico',
  'Ruanda',
  'Rumänien',
  'Russland',
  'Réunion',
  'Saint Kitts und Nevis',
  'Sambia',
  'Samoa',
  'San Marino',
  'Sao Tomé und Principe',
  'Saudi-Arabien',
  'Schweden',
  'Schweiz',
  'Senegal',
  'Serbien',
  'Seychellen',
  'Sierra Leone',
  'Simbabwe',
  'Singapur',
  'Sint Maarten',
  'Slowakei (Slowakische Republik)',
  'Slowenien',
  'Solomon-Inseln',
  'Somalia',
  'Spanien',
  'Sri Lanka',
  'St. Barthélemy',
  'St. Helena',
  'St. Lucia',
  'St. Martin',
  'St. Pierre und Miquelon',
  'St. Vincent und die Grenadinen',
  'Staat der Vatikanstadt',
  'Sudan',
  'Suriname',
  'Svalbard und Jan Mayen',
  'Swasiland',
  'Syrien',
  'Südafrika',
  'Südgeorgien und die Südlichen Sandwichinseln',
  'Südkorea',
  'Südsudan',
  'Tadschikistan',
  'Taiwan',
  'Tansania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad und Tobago',
  'Tschad',
  'Tschechien',
  'Tunesien',
  'Turkmenistan',
  'Turks- und Caicosinseln',
  'Tuwalu',
  'Türkei',
  'USA',
  'Uganda',
  'Ukraine',
  'Ungarn',
  'Uruguay',
  'Usbekistan',
  'Vanuatu',
  'Venezuela',
  'Vereinigte Arabische Emirate',
  'Vereinigtes Königreich',
  'Vietnam',
  'Wallis und Futuna',
  'Weihnachtsinsel',
  'Weißrussland',
  'Westsahara',
  'Zentralafrikanische Republik',
  'Zypern',
  'Ägypten',
  'Äquatorialguinea',
  'Äthiopien',
  'Österreich'
]
