export default () => ([
  'Afghanistan',
  'Agypten',
  'Alandinseln',
  'Albanien',
  'Algerien',
  'Amerikanisch-Ozeanien',
  'Amerikanisch-Samoa',
  'Amerikanische Jungferninseln',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarktis',
  'Antigua und Barbuda',
  'Aquatorialguinea',
  'Argentinien',
  'Armenien',
  'Aruba',
  'Aserbaidschan',
  'Athiopien',
  'Australien',
  'Bahamas',
  'Bahrain',
  'Bangladesch',
  'Barbados',
  'Belgien',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Birma (Myanmar)',
  'Bolivien',
  'Bonaire',
  'Bosnien und Herzegowina',
  'Botswana',
  'Bouvetinsel',
  'Brasilien',
  'Britische Jungferninseln',
  'Britisches Territorium im Indischen Ozean',
  'Brunei',
  'Bulgarien',
  'Burkina Faso',
  'Burundi',
  'Chile',
  'China',
  'Cookinseln',
  'Costa Rica',
  'Curacao',
  'Danemark',
  'Deutschland',
  'Dom. Republik',
  'Dominica',
  'Dschibuti',
  'Ecuador',
  'Ehemalige jugoslawische Republik Mazedonien',
  'El Salvador',
  'Elfenbeinkuste',
  'Eritrea',
  'Estland',
  'Falklandinseln',
  'Faroer-Inseln',
  'Fidschi',
  'Finnland',
  'Frankreich',
  'Franzosisch-Guayana',
  'Franzosisch-Polynesien',
  'Franzosische Sud- und Antarktisgebiete',
  'Gabun',
  'Gambia',
  'Georgien',
  'Ghana',
  'Gibraltar',
  'Grenada',
  'Griechenland',
  'Gronland',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard- und McDonald-Inseln',
  'Honduras',
  'Hongkong',
  'Indien',
  'Indonesien',
  'Insel Man',
  'Irak',
  'Iran (Islamische Republik)',
  'Irland',
  'Island',
  'Israel',
  'Italien',
  'Jamaika',
  'Japan',
  'Jemen',
  'Jersey',
  'Jordanien',
  'Kaimaninseln',
  'Kambodscha',
  'Kamerun',
  'Kanada',
  'Kapverden',
  'Kasachstan',
  'Katar',
  'Kenia',
  'Kirgistan',
  'Kiribati',
  'Kokosinseln',
  'Kolumbien',
  'Komoren',
  'Kongo',
  'Kongo (Republik Kongo)',
  'Kosovo',
  'Kroatien',
  'Kuba',
  'Kuwait',
  'Laos',
  'Lesotho',
  'Lettland',
  'Libanon',
  'Liberia',
  'Libysch-Arabische Dschamahirija',
  'Liechtenstein',
  'Litauen',
  'Luxemburg',
  'Macau',
  'Madagaskar',
  'Malawi',
  'Malaysia',
  'Malediven',
  'Mali',
  'Malta',
  'Marokko',
  'Marshall-Inseln',
  'Martinique',
  'Mauretanien',
  'Mauritius',
  'Mayotte',
  'Mexiko',
  'Mikronesien',
  'Moldau (Republik Moldau)',
  'Monaco',
  'Mongolei',
  'Montenegro',
  'Montserrat',
  'Mosambik',
  'Namibia',
  'Nauru',
  'Nepal',
  'Neukaledonien',
  'Neuseeland',
  'Niederlande',
  'Niger',
  'Nigeria',
  'Nikaragua',
  'Niue',
  'Nordkorea',
  'Nordliche Marianen',
  'Norfolkinsel',
  'Norwegen',
  'Oman',
  'Osterreich',
  'Pakistan',
  'Palastinensische Autonomiegebiete',
  'Palau',
  'Panama',
  'Papua-Neuguinea',
  'Paraguay',
  'Peru',
  'Philippinen',
  'Pitcairn',
  'Polen',
  'Portugal',
  'Puerto Rico',
  'Reunion',
  'Ruanda',
  'Rumanien',
  'Russland',
  'Saint Kitts und Nevis',
  'Sambia',
  'Samoa',
  'San Marino',
  'Sao Tome und Principe',
  'Saudi-Arabien',
  'Schweden',
  'Schweiz',
  'Senegal',
  'Serbien',
  'Seychellen',
  'Sierra Leone',
  'Simbabwe',
  'Singapur',
  'Sint Maarten',
  'Slowakei (Slowakische Republik)',
  'Slowenien',
  'Solomon-Inseln',
  'Somalia',
  'Spanien',
  'Sri Lanka',
  'St. Barthelemy',
  'St. Helena',
  'St. Lucia',
  'St. Martin',
  'St. Pierre und Miquelon',
  'St. Vincent und die Grenadinen',
  'Staat der Vatikanstadt',
  'Sudafrika',
  'Sudan',
  'Sudgeorgien und die Sudlichen Sandwichinseln',
  'Sudkorea',
  'Sudsudan',
  'Suriname',
  'Svalbard und Jan Mayen',
  'Swasiland',
  'Syrien',
  'Tadschikistan',
  'Taiwan',
  'Tansania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad und Tobago',
  'Tschad',
  'Tschechien',
  'Tunesien',
  'Turkei',
  'Turkmenistan',
  'Turks- und Caicosinseln',
  'Tuwalu',
  'USA',
  'Uganda',
  'Ukraine',
  'Ungarn',
  'Uruguay',
  'Usbekistan',
  'Vanuatu',
  'Venezuela',
  'Vereinigte Arabische Emirate',
  'Vereinigtes Konigreich',
  'Vietnam',
  'Wallis und Futuna',
  'Weihnachtsinsel',
  'Weißrussland',
  'Westsahara',
  'Zentralafrikanische Republik',
  'Zypern'
])
