export default [
  'Afghanistan',
  'Afrique du Sud',
  'Albanie',
  'Algérie',
  'Allemagne',
  'Andorre',
  'Angola',
  'Anguilla',
  'Antarctique',
  'Antigua et Barbuda',
  'Arabie saoudite',
  'Argentine',
  'Arménie',
  'Aruba',
  'Australie',
  'Autriche',
  'Azerbaïdjan',
  'Bahamas',
  'Bahreïn',
  'Bangladesh',
  'Barbade',
  'Belgique',
  'Belize',
  'Bermudes',
  'Bhoutan',
  'Biélorussie',
  'Bolivie',
  'Bonaire, Saint-Eustache et Saba',
  'Bosnie-Herzégovine',
  'Botswana',
  'Brunéi Darussalam',
  'Brésil',
  'Bulgarie',
  'Burkina Faso',
  'Burundi',
  'Bénin',
  'Cambodge',
  'Cameroun',
  'Canada',
  'Cap-Vert',
  'Centrafrique',
  'Chili',
  'Chine',
  'Chypre',
  'Colombie',
  'Comores',
  'Congo-Brazzaville',
  'Corée du Nord',
  'Corée du Sud',
  'Costa Rica',
  'Croatie',
  'Cuba',
  'Curaçao',
  'Côte d\'Ivoire',
  'Danemark',
  'Djibouti',
  'Dominique',
  'Espagne',
  'Estonie',
  'Fidji',
  'Finlande',
  'France',
  'Gabon',
  'Gambie',
  'Ghana',
  'Gibraltar',
  'Grenade',
  'Groenland',
  'Grèce',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernesey',
  'Guinée',
  'Guinée équatoriale',
  'Guinée-Bissau',
  'Guyana',
  'Guyane',
  'Géorgie',
  'Géorgie du Sud-et-les îles Sandwich du Sud',
  'Haïti',
  'Honduras',
  'Hong Kong',
  'Hongrie',
  'Inde',
  'Indonésie',
  'Irak',
  'Iran',
  'Irlande',
  'Islande',
  'Israël',
  'Italie',
  'Jamaïque',
  'Japon',
  'Jersey',
  'Jordanie',
  'Kazakhstan',
  'Kenya',
  'Kirghizistan',
  'Kiribati',
  'Kosovo',
  'Koweït',
  'Laos',
  'Lesotho',
  'Lettonie',
  'Liban',
  'Liberia',
  'Libye',
  'Liechtenstein',
  'Lituanie',
  'Luxembourg',
  'Macao',
  'Macédoine',
  'Madagascar',
  'Malaisie',
  'Malawi',
  'Maldives',
  'Mali',
  'Malte',
  'Maroc',
  'Martinique',
  'Maurice',
  'Mauritanie',
  'Mayotte',
  'Mexique',
  'Micronésie',
  'Moldavie',
  'Monaco',
  'Mongolie',
  'Montserrat',
  'Monténégro',
  'Mozambique',
  'Myanmar',
  'Namibie',
  'Nauru',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Nioué',
  'Norvège',
  'Nouvelle-Calédonie',
  'Nouvelle-Zélande',
  'Népal',
  'Oman',
  'Ouganda',
  'Ouzbékistan',
  'Pakistan',
  'Palaos',
  'Panama',
  'Papouasie-Nouvelle Guinée',
  'Paraguay',
  'Pays-Bas',
  'Philippines',
  'Pitcairn',
  'Pologne',
  'Polynésie Française',
  'Porto Rico',
  'Portugal',
  'Pérou',
  'Qatar',
  'RDC',
  'Roumanie',
  'Royaume-Uni',
  'Russie',
  'Rwanda',
  'République Dominicaine',
  'République tchèque',
  'Réunion',
  'Sahara Occidental',
  'Saint-Barthélemy',
  'Saint-Christophe-et-Niévès',
  'Saint-Marin',
  'Saint-Martin',
  'Saint-Martin',
  'Saint-Pierre et Miquelon',
  'Saint-Vincent-et-les-Grenadines',
  'Sainte-Hélène',
  'Sainte-Lucie',
  'Salvador',
  'Samoa',
  'Samoa américaines',
  'Serbie',
  'Seychelles',
  'Sierra Leone',
  'Singapour',
  'Slovaquie',
  'Slovénie',
  'Somalie',
  'Soudan',
  'Sri Lanka',
  'Sud-Soudan',
  'Suisse',
  'Surinam',
  'Suède',
  'Svalbard et Jan Mayen',
  'Swaziland',
  'Syrie',
  'São Tomé-et-Príncipe',
  'Sénégal',
  'Tadjikistan',
  'Tanzanie',
  'Taïwan',
  'Tchad',
  'Terres australes françaises',
  'Territoire britannique de l\'océan Indien',
  'Territoire palestinien',
  'Thaïlande',
  'Timor Oriental',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad et Tobago',
  'Tunisie',
  'Turkménistan',
  'Turquie',
  'Tuvalu',
  'Ukraine',
  'Uruguay',
  'Vanuatu',
  'Vatican',
  'Vietnam',
  'Vénézuéla',
  'Wallis-et-Futuna',
  'Yémen',
  'Zambie',
  'Zimbabwe',
  'Égypte',
  'Émirats Arabes Unis',
  'Équateur',
  'Érythrée',
  'États-Unis',
  'Éthiopie',
  'Île Bouvet',
  'Île Christmas',
  'Île Heard et îles McDonald',
  'Île Norfolk',
  'Île de Man',
  'Îles Caïmans',
  'Îles Cocos',
  'Îles Cook',
  'Îles Féroé',
  'Îles Malouines',
  'Îles Mariannes du Nord',
  'Îles Marshall',
  'Îles Salomon',
  'Îles Turques-et-Caïques',
  'Îles Vierges',
  'Îles Vierges des États-Unis',
  'Îles mineures éloignées des États-Unis',
  'Îles Åland'
]
