export default () => ([
  'Afghanistan',
  'Afrique du Sud',
  'Albanie',
  'Algerie',
  'Allemagne',
  'Andorre',
  'Angola',
  'Anguilla',
  'Antarctique',
  'Antigua et Barbuda',
  'Arabie saoudite',
  'Argentine',
  'Armenie',
  'Aruba',
  'Australie',
  'Autriche',
  'Azerbaidjan',
  'Bahamas',
  'Bahrein',
  'Bangladesh',
  'Barbade',
  'Belgique',
  'Belize',
  'Benin',
  'Bermudes',
  'Bhoutan',
  'Bielorussie',
  'Bolivie',
  'Bonaire, Saint-Eustache et Saba',
  'Bosnie-Herzegovine',
  'Botswana',
  'Bresil',
  'Brunei Darussalam',
  'Bulgarie',
  'Burkina Faso',
  'Burundi',
  'Cambodge',
  'Cameroun',
  'Canada',
  'Cap-Vert',
  'Centrafrique',
  'Chili',
  'Chine',
  'Chypre',
  'Colombie',
  'Comores',
  'Congo-Brazzaville',
  'Coree du Nord',
  'Coree du Sud',
  'Costa Rica',
  'Cote d\'Ivoire',
  'Croatie',
  'Cuba',
  'Curacao',
  'Danemark',
  'Djibouti',
  'Dominique',
  'Egypte',
  'Emirats Arabes Unis',
  'Equateur',
  'Erythree',
  'Espagne',
  'Estonie',
  'Etats-Unis',
  'Ethiopie',
  'Fidji',
  'Finlande',
  'France',
  'Gabon',
  'Gambie',
  'Georgie',
  'Georgie du Sud-et-les iles Sandwich du Sud',
  'Ghana',
  'Gibraltar',
  'Grece',
  'Grenade',
  'Groenland',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernesey',
  'Guinee',
  'Guinee equatoriale',
  'Guinee-Bissau',
  'Guyana',
  'Guyane',
  'Haiti',
  'Honduras',
  'Hong Kong',
  'Hongrie',
  'Ile Bouvet',
  'Ile Christmas',
  'Ile Heard et iles McDonald',
  'Ile Norfolk',
  'Ile de Man',
  'Iles Aland',
  'Iles Caimans',
  'Iles Cocos',
  'Iles Cook',
  'Iles Feroe',
  'Iles Malouines',
  'Iles Mariannes du Nord',
  'Iles Marshall',
  'Iles Salomon',
  'Iles Turques-et-Caiques',
  'Iles Vierges',
  'Iles Vierges des Etats-Unis',
  'Iles mineures eloignees des Etats-Unis',
  'Inde',
  'Indonesie',
  'Irak',
  'Iran',
  'Irlande',
  'Islande',
  'Israel',
  'Italie',
  'Jamaique',
  'Japon',
  'Jersey',
  'Jordanie',
  'Kazakhstan',
  'Kenya',
  'Kirghizistan',
  'Kiribati',
  'Kosovo',
  'Koweit',
  'Laos',
  'Lesotho',
  'Lettonie',
  'Liban',
  'Liberia',
  'Libye',
  'Liechtenstein',
  'Lituanie',
  'Luxembourg',
  'Macao',
  'Macedoine',
  'Madagascar',
  'Malaisie',
  'Malawi',
  'Maldives',
  'Mali',
  'Malte',
  'Maroc',
  'Martinique',
  'Maurice',
  'Mauritanie',
  'Mayotte',
  'Mexique',
  'Micronesie',
  'Moldavie',
  'Monaco',
  'Mongolie',
  'Montenegro',
  'Montserrat',
  'Mozambique',
  'Myanmar',
  'Namibie',
  'Nauru',
  'Nepal',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Nioue',
  'Norvege',
  'Nouvelle-Caledonie',
  'Nouvelle-Zelande',
  'Oman',
  'Ouganda',
  'Ouzbekistan',
  'Pakistan',
  'Palaos',
  'Panama',
  'Papouasie-Nouvelle Guinee',
  'Paraguay',
  'Pays-Bas',
  'Perou',
  'Philippines',
  'Pitcairn',
  'Pologne',
  'Polynesie Francaise',
  'Porto Rico',
  'Portugal',
  'Qatar',
  'RDC',
  'Republique Dominicaine',
  'Republique tcheque',
  'Reunion',
  'Roumanie',
  'Royaume-Uni',
  'Russie',
  'Rwanda',
  'Sahara Occidental',
  'Saint-Barthelemy',
  'Saint-Christophe-et-Nieves',
  'Saint-Marin',
  'Saint-Martin',
  'Saint-Martin',
  'Saint-Pierre et Miquelon',
  'Saint-Vincent-et-les-Grenadines',
  'Sainte-Helene',
  'Sainte-Lucie',
  'Salvador',
  'Samoa',
  'Samoa americaines',
  'Sao Tome-et-Principe',
  'Senegal',
  'Serbie',
  'Seychelles',
  'Sierra Leone',
  'Singapour',
  'Slovaquie',
  'Slovenie',
  'Somalie',
  'Soudan',
  'Sri Lanka',
  'Sud-Soudan',
  'Suede',
  'Suisse',
  'Surinam',
  'Svalbard et Jan Mayen',
  'Swaziland',
  'Syrie',
  'Tadjikistan',
  'Taiwan',
  'Tanzanie',
  'Tchad',
  'Terres australes francaises',
  'Territoire britannique de l\'ocean Indien',
  'Territoire palestinien',
  'Thailande',
  'Timor Oriental',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad et Tobago',
  'Tunisie',
  'Turkmenistan',
  'Turquie',
  'Tuvalu',
  'Ukraine',
  'Uruguay',
  'Vanuatu',
  'Vatican',
  'Venezuela',
  'Vietnam',
  'Wallis-et-Futuna',
  'Yemen',
  'Zambie',
  'Zimbabwe'
])
