export default [
  'Afganistán',
  'Albania',
  'Alemania',
  'Andorra',
  'Angola',
  'Anguila',
  'Antigua y Barbuda',
  'Antártida',
  'Arabia Saudí',
  'Argelia',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaiyán',
  'Bahamas',
  'Bahréin',
  'Bangladesh',
  'Barbados',
  'Belice',
  'Benín',
  'Bermudas',
  'Bielorrusia',
  'Bolivia',
  'Bonaire',
  'Bosnia-Herzegovina',
  'Botsuana',
  'Brasil',
  'Brunéi',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Bután',
  'Bélgica',
  'Cabo Verde',
  'Camboya',
  'Camerún',
  'Canadá',
  'Chad',
  'Chile',
  'China',
  'Chipre',
  'Ciudad del Vaticano',
  'Colombia',
  'Comoras',
  'Congo Democrático',
  'Congo [República]',
  'Corea del Norte',
  'Corea del Sur',
  'Costa Rica',
  'Costa de Marfil',
  'Croacia',
  'Cuba',
  'Curazao',
  'Dinamarca',
  'Dominica',
  'Ecuador',
  'Egipto',
  'El Salvador',
  'Emiratos Árabes Unidos',
  'Eritrea',
  'Eslovaquia',
  'Eslovenia',
  'España',
  'Estados Unidos',
  'Estonia',
  'Etiopía',
  'Filipinas',
  'Finlandia',
  'Fiyi',
  'Francia',
  'Gabón',
  'Gambia',
  'Georgia',
  'Ghana',
  'Gibraltar',
  'Granada',
  'Grecia',
  'Groenlandia',
  'Guadalupe',
  'Guam',
  'Guatemala',
  'Guayana Francesa',
  'Guernsey',
  'Guinea',
  'Guinea Ecuatorial',
  'Guinea-Bissáu',
  'Guyana',
  'Haití',
  'Holanda',
  'Honduras',
  'Hong Kong',
  'Hungría',
  'India',
  'Indonesia',
  'Irak',
  'Irlanda',
  'Irán',
  'Isla Bouvet',
  'Isla Christmas',
  'Isla Niue',
  'Isla Norfolk',
  'Isla de Man',
  'Islandia',
  'Islas Caimán',
  'Islas Cocos',
  'Islas Cook',
  'Islas Feroe',
  'Islas Georgia del Sur y Sandwich del Sur',
  'Islas Heard y McDonald',
  'Islas Malvinas',
  'Islas Marianas del Norte',
  'Islas Marshall',
  'Islas Pitcairn',
  'Islas Salomón',
  'Islas Turcas y Caicos',
  'Islas Vírgenes',
  'Islas Vírgenes de los Estados Unidos',
  'Islas de Åland',
  'Islas menores alejadas de los Estados Unidos',
  'Israel',
  'Italia',
  'Jamaica',
  'Japón',
  'Jersey',
  'Jordania',
  'Kazajstán',
  'Kenia',
  'Kirguistán',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Laos',
  'Lesotho',
  'Letonia',
  'Liberia',
  'Libia',
  'Liechtenstein',
  'Lituania',
  'Luxemburgo',
  'Líbano',
  'Macao',
  'Macedonia',
  'Madagascar',
  'Malasia',
  'Malaui',
  'Maldivas',
  'Mali',
  'Malta',
  'Marruecos',
  'Martinica',
  'Mauricio',
  'Mauritania',
  'Mayotte',
  'Micronesia',
  'Moldavia',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Mozambique',
  'Myanmar [Birmania]',
  'México',
  'Mónaco',
  'Namibia',
  'Nauru',
  'Nepal',
  'Nicaragua',
  'Nigeria',
  'Noruega',
  'Nueva Caledonia',
  'Nueva Zelanda',
  'Níger',
  'Omán',
  'Pakistán',
  'Palaos',
  'Panamá',
  'Papúa-Nueva Guinea',
  'Paraguay',
  'Perú',
  'Polinesia Francesa',
  'Polonia',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Reino Unido',
  'República Centroafricana',
  'República Checa',
  'República Dominicana',
  'Reunión',
  'Ruanda',
  'Rumanía',
  'Rusia',
  'Samoa',
  'Samoa Americana',
  'San Bartolomé',
  'San Cristóbal y Nieves',
  'San Marino',
  'San Martín',
  'San Martín',
  'San Pedro y Miquelón',
  'San Vicente y las Granadinas',
  'Santa Elena',
  'Santa Lucía',
  'Santo Tomé y Príncipe',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leona',
  'Singapur',
  'Siria',
  'Somalia',
  'Sri Lanka',
  'Suazilandia',
  'Sudáfrica',
  'Sudán',
  'Sudán del Sur',
  'Suecia',
  'Suiza',
  'Surinam',
  'Svalbard y Jan Mayen',
  'Sáhara Occidental',
  'Tailandia',
  'Taiwán',
  'Tanzania',
  'Tayikistán',
  'Territorio Británico del Océano Índico',
  'Territorios Australes Franceses',
  'Territorios Palestinos',
  'Timor Oriental',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad y Tobago',
  'Turkmenistán',
  'Turquía',
  'Tuvalu',
  'Túnez',
  'Ucrania',
  'Uganda',
  'Uruguay',
  'Uzbekistán',
  'Vanuatu',
  'Venezuela',
  'Vietnam',
  'Wallis y Futuna',
  'Yemen',
  'Yibuti',
  'Zambia',
  'Zimbawe'
]
