export default () => ([
  'Afganistan',
  'Albania',
  'Alemania',
  'Andorra',
  'Angola',
  'Anguila',
  'Antartida',
  'Antigua y Barbuda',
  'Arabia Saudi',
  'Argelia',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaiyan',
  'Bahamas',
  'Bahrein',
  'Bangladesh',
  'Barbados',
  'Belgica',
  'Belice',
  'Benin',
  'Bermudas',
  'Bielorrusia',
  'Bolivia',
  'Bonaire',
  'Bosnia-Herzegovina',
  'Botsuana',
  'Brasil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Butan',
  'Cabo Verde',
  'Camboya',
  'Camerun',
  'Canada',
  'Chad',
  'Chile',
  'China',
  'Chipre',
  'Ciudad del Vaticano',
  'Colombia',
  'Comoras',
  'Congo Democratico',
  'Congo Republica',
  'Corea del Norte',
  'Corea del Sur',
  'Costa Rica',
  'Costa de Marfil',
  'Croacia',
  'Cuba',
  'Curazao',
  'Dinamarca',
  'Dominica',
  'Ecuador',
  'Egipto',
  'El Salvador',
  'Emiratos Arabes Unidos',
  'Eritrea',
  'Eslovaquia',
  'Eslovenia',
  'Espana',
  'Estados Unidos',
  'Estonia',
  'Etiopia',
  'Filipinas',
  'Finlandia',
  'Fiyi',
  'Francia',
  'Gabon',
  'Gambia',
  'Georgia',
  'Ghana',
  'Gibraltar',
  'Granada',
  'Grecia',
  'Groenlandia',
  'Guadalupe',
  'Guam',
  'Guatemala',
  'Guayana Francesa',
  'Guernsey',
  'Guinea',
  'Guinea Ecuatorial',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Holanda',
  'Honduras',
  'Hong Kong SAR',
  'Hungria',
  'India',
  'Indonesia',
  'Irak',
  'Iran',
  'Irlanda',
  'Isla Bouvet',
  'Isla Christmas',
  'Isla Niue',
  'Isla Norfolk',
  'Isla de Man',
  'Islandia',
  'Islas Caiman',
  'Islas Cocos',
  'Islas Cook',
  'Islas Feroe',
  'Islas Georgia del Sur y Sandwich del Sur',
  'Islas Heard y McDonald',
  'Islas Malvinas',
  'Islas Marianas del Norte',
  'Islas Marshall',
  'Islas Pitcairn',
  'Islas Salomon',
  'Islas Turcas y Caicos',
  'Islas Virgenes',
  'Islas Virgenes de los Estados Unidos',
  'Islas de Aland',
  'Islas menores alejadas de los Estados Unidos',
  'Israel',
  'Italia',
  'Jamaica',
  'Japon',
  'Jersey',
  'Jordania',
  'Kazajstan',
  'Kenia',
  'Kirguistan',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Laos',
  'Lesotho',
  'Letonia',
  'Libano',
  'Liberia',
  'Libia',
  'Liechtenstein',
  'Lituania',
  'Luxemburgo',
  'Macao SAR',
  'Macedonia',
  'Madagascar',
  'Malasia',
  'Malaui',
  'Maldivas',
  'Mali',
  'Malta',
  'Marruecos',
  'Martinica',
  'Mauricio',
  'Mauritania',
  'Mayotte',
  'Mexico',
  'Micronesia',
  'Moldavia',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Mozambique',
  'Myanmar Birmania',
  'Namibia',
  'Nauru',
  'Nepal',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Noruega',
  'Nueva Caledonia',
  'Nueva Zelanda',
  'Oman',
  'Pakistan',
  'Palaos',
  'Panama',
  'Papua-Nueva Guinea',
  'Paraguay',
  'Peru',
  'Polinesia Francesa',
  'Polonia',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Reino Unido',
  'Republica Centroafricana',
  'Republica Checa',
  'Republica Dominicana',
  'Reunion',
  'Ruanda',
  'Rumania',
  'Rusia',
  'Sahara Occidental',
  'Samoa',
  'Samoa Americana',
  'San Bartolome',
  'San Cristobal y Nieves',
  'San Marino',
  'San Martin',
  'San Martin2',
  'San Pedro y Miquelon',
  'San Vicente y las Granadinas',
  'Santa Elena',
  'Santa Lucia',
  'Santo Tome y Principe',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leona',
  'Singapur',
  'Siria',
  'Somalia',
  'Sri Lanka',
  'Suazilandia',
  'Sudafrica',
  'Sudan',
  'Sudan del Sur',
  'Suecia',
  'Suiza',
  'Surinam',
  'Svalbard y Jan Mayen',
  'Tailandia',
  'Taiwan',
  'Tanzania',
  'Tayikistan',
  'Territorio Britanico del Oceano Indico',
  'Territorios Australes Franceses',
  'Territorios Palestinos',
  'Timor Oriental',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad y Tobago',
  'Tunez',
  'Turkmenistan',
  'Turquia',
  'Tuvalu',
  'Ucrania',
  'Uganda',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Vietnam',
  'Wallis y Futuna',
  'Yemen',
  'Yibuti',
  'Zambia',
  'Zimbawe'
])
